#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_cLeonDecoy_Base

#include "Basic.hpp"

#include "BP_cLeonDecoy_Base_classes.hpp"
#include "BP_cLeonDecoy_Base_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_cLeonDecoy_Base.BP_cLeonDecoy_Base_C.ExecuteUbergraph_BP_cLeonDecoy_Base
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_cLeonDecoy_Base_C::ExecuteUbergraph_BP_cLeonDecoy_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonDecoy_Base_C", "ExecuteUbergraph_BP_cLeonDecoy_Base");

	Params::BP_cLeonDecoy_Base_C_ExecuteUbergraph_BP_cLeonDecoy_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_cLeonDecoy_Base.BP_cLeonDecoy_Base_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_cLeonDecoy_Base_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonDecoy_Base_C", "ReceiveTick");

	Params::BP_cLeonDecoy_Base_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
