#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RandomObject_PresetType

#include "Basic.hpp"

#include "BP_RandomObject_PresetType_classes.hpp"
#include "BP_RandomObject_PresetType_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_RandomObject_PresetType.BP_RandomObject_PresetType_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_RandomObject_PresetType_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RandomObject_PresetType_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RandomObject_PresetType.BP_RandomObject_PresetType_C.SetPreviewIndex
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsError                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RandomObject_PresetType_C::SetPreviewIndex(int32 Index_0, bool* IsError)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RandomObject_PresetType_C", "SetPreviewIndex");

	Params::BP_RandomObject_PresetType_C_SetPreviewIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (IsError != nullptr)
		*IsError = Parms.IsError;
}


// Function BP_RandomObject_PresetType.BP_RandomObject_PresetType_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_RandomObject_PresetType_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RandomObject_PresetType_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RandomObject_PresetType.BP_RandomObject_PresetType_C.OnRep_CurrentIndex
// (BlueprintCallable, BlueprintEvent)

void ABP_RandomObject_PresetType_C::OnRep_CurrentIndex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RandomObject_PresetType_C", "OnRep_CurrentIndex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RandomObject_PresetType.BP_RandomObject_PresetType_C.IndexUpdate
// (BlueprintCallable, BlueprintEvent)

void ABP_RandomObject_PresetType_C::IndexUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RandomObject_PresetType_C", "IndexUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RandomObject_PresetType.BP_RandomObject_PresetType_C.ExecuteUbergraph_BP_RandomObject_PresetType
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RandomObject_PresetType_C::ExecuteUbergraph_BP_RandomObject_PresetType(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RandomObject_PresetType_C", "ExecuteUbergraph_BP_RandomObject_PresetType");

	Params::BP_RandomObject_PresetType_C_ExecuteUbergraph_BP_RandomObject_PresetType Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
