#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RandomObject_PresetType

#include "Basic.hpp"

#include "ST_cLeonRandomPresetActors_structs.hpp"
#include "Engine_structs.hpp"
#include "BP_RandomObject_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RandomObject_PresetType.BP_RandomObject_PresetType_C
// 0x0028 (0x02E0 - 0x02B8)
class ABP_RandomObject_PresetType_C final : public ABP_RandomObject_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_RandomObject_PresetType_C;       // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Cube;                                              // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         PreviewIndex;                                      // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         CurrentIndex;                                      // 0x02CC(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	TArray<struct FST_cLeonRandomPresetActors>    Actors;                                            // 0x02D0(0x0010)(Edit, BlueprintVisible)

public:
	void UserConstructionScript();
	void SetPreviewIndex(int32 Index_0, bool* IsError);
	void ReceiveBeginPlay();
	void OnRep_CurrentIndex();
	void IndexUpdate();
	void ExecuteUbergraph_BP_RandomObject_PresetType(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RandomObject_PresetType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RandomObject_PresetType_C")
	}
	static class ABP_RandomObject_PresetType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RandomObject_PresetType_C>();
	}
};
DUMPER7_ASSERTS_ABP_RandomObject_PresetType_C;

SDK_NAMESPACE_END
