#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_cLeonRandomPresetActors

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_cLeonRandomPresetActors.ST_cLeonRandomPresetActors
// 0x0010 (0x0010 - 0x0000)
struct FST_cLeonRandomPresetActors final
{
public:
	TArray<class AActor*>                         Actors_5_E8532C39451727C52C9E1CB432A0A599;         // 0x0000(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
};
DUMPER7_ASSERTS_FST_cLeonRandomPresetActors;

SDK_NAMESPACE_END
