#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace WBP_LockOn_0 { class UWBP_LockOn_C; }

namespace ABP_FPS_HandBone_Ver2_Skeletal { struct FAnimBlueprintGeneratedConstantData; }

namespace WBP_LockOn { class UWBP_LockOn_C; }

namespace ABP_MagicHand { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Bell { struct FAnimBlueprintGeneratedConstantData; }


namespace ABP_Penguin
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_LINK_Penguin_V2
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_MainCharacter_PaintMan
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_BigPen
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_MiniPenguin
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_EnemyPenguin
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
